schema_version: 1

context:
  version: "0.1.0"

package:
  name: template-cpp-project
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - mkdir -p build
    - |
      cmake -B build -S . \
        -GNinja \
        ${CMAKE_ARGS} \
        -DCMAKE_CXX_STANDARD=17 \
        -Dtemplate-cpp-project_DEVELOPER_MODE=OFF
    - cmake --build build --config Release
    - cmake --install build --config Release

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake >=3.24,<4
    - ninja >=1.12.1,<2
    - ccache >=4.10.1,<5
    - pkg-config >=0.29.2,<0.30
  host:
    - fmt >=11.0.2,<12
  run:
    - fmt >=11.0.2,<12

tests:
  - package_contents:
      files:
        - if: unix
          then:
            - lib/libtemplate-cpp-project.a
            - lib/cmake/template-cpp-project/template-cpp-projectConfig.cmake
        - if: win
          then:
            - Library/lib/template-cpp-project.lib
            - Library/lib/cmake/template-cpp-project/template-cpp-projectConfig.cmake