CALL "%VCINSTALLDIR%/Auxiliary/vcvarsall.bat"
SET CMAKE_PLAT=
SET CMAKE_GENERATOR_PLATFORM=
SET CMAKE_GENERATOR_TOOLSET=
SET CMAKE_GENERATOR=
SET CMAKE_GEN=

IF "%BUILD_PREFIX%" == "" (
    SET BUILD_PREFIX="%CONDA_PREFIX%"
)

IF "%PREFIX%" == "" (
    SET BUILD_PREFIX="%CONDA_PREFIX%"
)

IF "%INSTALL_PREFIX%" == "" (
    SET BUILD_PREFIX="%PREFIX%"
)

IF "%PROJECT_ROOT%" == "" (
    SET BUILD_PREFIX="%PIXI_PROJECT_ROOT%"
)

SET PROJECT_TOOLCHAIN_FILE="%PROJECT_ROOT%/toolchains/windows.cmake"

